name: Test Cloudflare-Pages-Variable-Action
on:
  push:
    paths:
      - action.yaml
      - scripts/**
      - .github/workflows/test.yaml
      
concurrency:
  group: ${{ github.workflow }}
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Update variable value using Cloudflare-Pages-Variable-Action
        uses: AnimMouse/Cloudflare-Pages-Variable-Action@main
        with:
          method: update
          variable_name: ${{ vars.CLOUDFLARE_VARIABLE_NAME }}
          variable_value: ${{ github.run_id }}
          project_name: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          account_id: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          
      - name: Get variable value using Cloudflare-Pages-Variable-Action
        id: variable
        uses: AnimMouse/Cloudflare-Pages-Variable-Action@main
        with:
          method: get
          variable_name: ${{ vars.CLOUDFLARE_VARIABLE_NAME }}
          project_name: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          account_id: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          
      - name: Echo current variable value
        run: echo ${{ steps.variable.outputs.variable_value }}